const router = require('express').Router();
const nodemailer = require('nodemailer');
const OTP = require('../models/OTP');
const User = require('../models/User');

const transporter = nodemailer.createTransport({
    port: 465,               // true for 465, false for other ports
    host: "smtp.gmail.com",
       auth: {
            user: process.env.EMAIL,
            pass: process.env.PASSWORD,
         },
    secure: true,
    });

const header = `<p style="font-size:16px;">To verify your email address, please use the following One Time Password (OTP):</p>`;
const body = `<p>Please do not share OTP details with anyone.</p>`;
const body2 = `<br/><p style="font-size:16px;">Developed by <b>Akshay Nair</b>;
 <a href="https://www.linkedin.com/in/snakshay">Connect with me</a>. Website created using MERN and AWS S3 bucket.</p>`;
const footer = `<br/><br/><p style="width:80%;margin:auto";font-size:12px;justify-content: center>Note: This is an autogenerated mail. Please do not reply to this mail. By registering you agree to our terms and conditions. Please note Social dosen't gaurantee if any user senstive data is comprimised. Thanks for using Social!</p>`;


router.post('/',async (req,res)=>{
    try{
        const user = await User.findOne({ email: req.body.email });
        if (user) {
            return res.status(403).json('Email id already exists!')
        }
        const otp = Math.floor(100000 + Math.random() * 900000);
        const otpData ={
            otp:otp,
            email:req.body.email
        }
        await OTP.updateOne({email:req.body.email},{$set:otpData},{upsert:true});
        const mailData = {
            from: 'socialProd.akshay@gmail.com',
            to: req.body.email,
            subject: 'Thank you for registering with Social. Please verify your account ',
            html:`${header}<h2>${otp}</h2>${body+body2+footer}`
            };
        
        transporter.sendMail(mailData, function (err, info) {
            if(err){
                console.log(err);
                return res.status(500).send(err);
            }
            
            console.log(info);
            res.status(200).json('OTP send successfull')
        });
    }catch(err){
        console.log(err);
        res.status(500).json(err);
    }
    
})

module.exports = router